alphagov/govuk-rfcs

rfc-081-approach-for-next-iteration-of-content-api.md
[This RFC](https://github.com/alphagov/govuk-rfcs/blob/3156c39e7cf2b375a5a8f3bd0fe39355fe42fbf2/rfc-081-approach-for-next-iteration-of-content-api.md) explains the approach we (the API for Content team) have taken towards defining the next iteration of the Content API. The Content API being the public endpoints that are served from the [Content Store](https://github.com/alphagov/content-store) on `www.gov.uk/api/content`.
As this is to be both a public and widely used internal API we felt it was prudent to put this to an RFC while it's still malleable to get wider feedback and awareness of things we haven't considered. 
Apologies this is so long - I didn't quite realise how much longer it was than most of the other RFC's until it'd been a while. So maybe find a comfy chair before settling …
=> RFC 81: Approach for next iteration of Content API

rfc-083-case-insensitive-routing.md
This RFC makes the argument for case insensitive routing on GOV.UK.
It was bought about by an issue seen by the Worldwide Publishing team where `whitehall` was receiving requests meant to be for `collections` since the requested page was below a prefix route, but the mixed-case base path wasn’t being matched to the equivalent lowercase exact base path claimed by `collections`.
I am aware that this has been requested before and generated some active discussion so I’d be interested to hear arguments from both sides.
=> RFC 83: Case insensitive routing

rfc-026-12-factor-rails-apps.md
Removes some &amp;nbsp;s and stray bullets from the conversion from
Confluence
=> Fix formatting of RFC 26

rfc-086-draft-stack-rummager.md
This RFC came out of a discussion about the needs of Content Tagger to
get per taxon metrics about tagged content, including draft taxons,
that led to a discussion about draft content in general, and how the
behaviour of rummager affects the draft stack.
=> RFC 86: Draft Stack Rummager

rfc-093-retire-govuk-cdn-logs-monitor.md
👉[Rendered version](https://github.com/alphagov/govuk-rfcs/blob/4df73d305361e24d6523e24037bd2886398cbb6a/rfc-093-retire-govuk-cdn-logs-monitor.md) 👈 
A proposal on why we should remove this application and the process we
should undertake.
Closing date: Wednesday 27th June
=> Retire GOV.UK CDN Logs Monitor

rfc-097-verify-specific-start-pages.md
👉 [Rendered Version](https://github.com/alphagov/govuk-rfcs/blob/hub-341-start-pages-for-verify/rfc-097-verify-specific-start-pages.md)
This document describes an approach for providing alternative service start pages
that will be displayed to users on a GOV.UK Verify single IDP journey.
Ported from `verify-architecture` repo, authored by Chris Clayson.
=> HUB-341: Start pages for GOV.UK Verify

rfc-098-csp-on-cdn.md, rfc-098-csp.md
The purpose of this RFC is to document why we're going to add a Content Security Policy, and to get consensus on how to implement it.
👉[Rendered version](https://github.com/alphagov/govuk-rfcs/blob/csp-on-cdn/rfc-098-csp.md)
=> RFC 98: Implement Content Security Policy in apps

rfc-100-linting.md
This RFC proposes a change our linting systems.
It is based on work by @theseanything to implement linting with Rubocop directly (https://github.com/alphagov/content-performance-manager/pull/1082), @alex-ju's work to implement frontend linting in the components (https://github.com/alphagov/govuk_publishing_components/pull/758) and @cbaines work to [properly lint all the repos](https://github.com/pulls?q=is%3Apr+author%3Acbaines+archived%3Afalse+linting+is%3Aclosed).   
👉[View it rendered](https://github.com/alphagov/govuk-rfcs/blob/linting/rfc-100-linting.md)
=> RFC 100: Improve linting

rfc-103-merge-dependabot-pull-requests-with-a-single-review.md
Closes on Wednesday the 17th of April.
=> RFC 103: Merge Dependabot Pull Requests with a single review

rfc-058-publishing-api-events.md
There looks to have been a bug with the govuk-rfc-bot which replaced the RFC with comments from the wiki. https://github.com/alphagov/govuk-rfcs/blob/94fa0dc/rfc-058-publishing-api-events.md
Original PR with Comments: https://github.com/alphagov/govuk-rfcs/pull/58
Orginial page in wiki: https://gov-uk.atlassian.net/wiki/spaces/GOVUK/pages/105611331/RFC+58++Publishing+API+Events
=> Restore RFC 58 from commit f32be298c

rfc-106-docker-for-local-development.md
In the next firebreak, we're thinking to overhaul GOV.UK's development environment. Before doing this, we'll have to choose an approach.
This RFC proposes to use Docker. But we know Docker isn't without problems, so this RFC also serves to collect feedback on the types of problems we're likely to see.
👉[Rendered version](https://github.com/alphagov/govuk-rfcs/blob/docker-for-local-development/rfc-106-docker-for-local-development.md)
=> RFC 106: Use Docker for local development 🐳

rfc-113-expanding-draft-access-for-unauthenticated-users.md
View rendered: https://github.com/alphagov/govuk-rfcs/blob/rfc-113/rfc-113-expanding-draft-access-for-unauthenticated-users.md
Hello :wave: this is an RFC about the expansion in access limiting that will be needed to support fact checking step-by-steps. Unfortunately the team is on a tight schedule so the work to implement this proposal will be ongoing during the time open for this RFC, so I'm kind of hoping that it won't be too controversial and be a useful source of documentation. This RFC will close on the 11th October.
TL;DR: We want to expand auth-bypass access to draft GOV.UK to allow multiple pages and their assets. As a user may not own these resources this process cannot be used to bypass access limiting on them. We will use link expansion to share an auth-bypass id to GOV.UK …
=> RFC 113: Expanding draft access for unauthenticated users

rfc-108-including-gem-component-assets.md
Alternative for the current model of including GOV.UK component assets in frontend applications.
👉 [Rendered version](https://github.com/alphagov/govuk-rfcs/blob/bc1ad0677abcbfdf48ba6bc0b2e0f24557e48e9a/rfc-108-including-gem-component-assets.md)
I've also started a [spike for the individual Sass inclusion](https://github.com/alphagov/govuk_publishing_components/pull/1159).
=> RFC 108 Include frontend gem component assets individually

rfc-116-store-attachment-data-in-content-items.md
**Deadline for discussion: 2020-01-31**
~**Deadline for discussion: 2020-01-24**~
[Rendered](https://github.com/alphagov/govuk-rfcs/blob/msw/rfc-116/rfc-116-store-attachment-data-in-content-items.md)
=> RFC 116: store attachment data in content items

rfc-116-store-attachment-data-in-content-items.md
This amends the RFC to resolve some misunderstandings with the approach
we'd be taking for this work. This change reflects a desire to no longer
pass HTML or Govspeak into content items for attachments and instead
pass in an id to reference which attachment should be rendered, the
rendering applications will then take this id and use a component to
render the resulting attachment.
=> Update RFC 116 to reflect revised featured_attachments approach

rfc-095-long-term-future-apps.md
This removes mention of content-audit-tool as it's now retired.
=> Remove content-audit-tool

rfc-123-github-actions-ci.md
- This RFC was requested by @kevindew [when I switched `alphagov/seal` to not build on Jenkins](https://github.com/alphagov/seal/pull/162#pullrequestreview-396261703). And he's had input on some of the words!
- I've tried to put [the words I wrote in response](https://github.com/alphagov/seal/pull/162#issuecomment-616423677) into better words here, but there's more paragraphs there so that comment is worth a read too.
- This is open for two weeks, until **midday on 2020-05-05**.
👉[Rendered version](https://github.com/alphagov/govuk-rfcs/blob/github-actions-ci/rfc-123-github-actions-ci.md)
=> RFC-123: GitHub Actions CI

rfc-134-govuk-wide-session-cookie-and-login.md
[Rendered](https://github.com/alphagov/govuk-rfcs/blob/msw/account-session/rfc-134-govuk-wide-session-cookie-and-login.md)
**Deadline:** 2021-02-09.
---
We propose introducing a new cookie, `__Host-govuk_account_session`,
which will be an essential cookie, but only set when a user signs in
to use personalised parts of GOV.UK (currently just the Transition
Checker).
Similarly to how our A/B tests work we will manage this cookie at the
Fastly layer, in Varnish Configuration Language (VCL), and use custom
request headers to pass the cookie value to our apps. We will also use
custom response headers to set a new cookie value.
We will create a new app to provide the internal account-supporting
API, and extend frontend to handle the login and logout process.
=> A GOV.UK-wide session cookie & login

rfc-135-updating-routes-in-router.md
[Rendered](https://github.com/alphagov/govuk-rfcs/blob/updating-routes-in-router/rfc-135-updating-routes-in-router.md)
**Deadline:** 2021-03-05
=> Updating routes in Router

rfc-136-remove-our-backup-cdn-in-gcp.md
✨ [Rendered](https://github.com/alphagov/govuk-rfcs/blob/remove-the-gcp-backup-cdn/rfc-136-remove-our-backup-cdn-in-gcp.md) ✨ 
**Deadline**: 2021-03-17
=> RFC to remove our Google Cloud CDN backup

rfc-134-govuk-wide-session-cookie-and-login.md
We had to change this to use samesite=lax because of issues with
cross-domain links.
The change has already been implemented, so this commit just updates
the RFC to reflect the current state.
=> Update session cookie in RFC 134

rfc-141-application-healthchecks.md
**Deadline for discussion:** 2021-04-16
[Rendered](https://github.com/alphagov/govuk-rfcs/blob/msw/application-healthchecks/rfc-141-application-healthchecks.md)
---
We currently use application healthchecks for three things:
- For load balancing, to determine if an instance is ready to serve
requests.
- For continuous deployments, to determine (along with other smoke
tests) if a release can be automatically pushed to production.
- For alerting, so that 2ndline know if an instance has a problem
which needs manual intervention to fix.
We implement healthchecks using the `GovukHealthcheck` module in
govuk_app_config.
Currently, a healthcheck response is always served with an HTTP status
of 200, and indicates in the body whether the instance's status is
"ok", "warning", or "critical". …
=> Application Healthchecks

rfc-142-add-interest-cohort-permssion-policy-header.md
👉🏻 [Rendered](https://github.com/alphagov/govuk-rfcs/blob/rfc-142-add-interest-cohort-permission-policy/rfc-142-add-interest-cohort-permssion-policy-header.md)
Many thanks to [Matt Hobbs](https://github.com/Nooshu) for a discussion paper on the issue from which many of the words for this RFC have been lifted.
Deadline: 2021-07-01
=> Add rfc 142 - interest cohort permission policy

rfc-144-consistent-cache-expiry.md
This proposes making the emergency banner deployment more reliable, by replacing the "display banner immediately" feature with a guarantee to display the banner within 15 minutes.
Rendered RFC: https://github.com/alphagov/govuk-rfcs/blob/bilbof/consistent-cache-expiry/rfc-144-consistent-cache-expiry.md
Deadline for feedback: Wed 1 December 2021.
The tl;dr is that the "display banner immediately" feature is implemented by purging four layers of caches. Our cache invalidation implementation is fragile and has caused problems, notably [this Nov 2021 incident](https://docs.google.com/document/d/1yXGQxQv0IdeWxVegf8UHatnIrCTbd-ZslZB8AxN11QU/edit#) (GDS internal doc).
We do not have an SLA to display the banner instantly. @nicholsj has confirmed that it is acceptable for the banner to appear on …
=> RFC 144 More reliable emergency banner deployment

rfc-145-unarchive-govuk_admin_template.md
This PR introduces RFC-145.
The [govuk-admin-template](https://github.com/alphagov/govuk_admin_template) gem has been deprecated for a while, and new GOV.UK admin applications should be built using the [layout component in govuk_publishing_components](https://govuk-publishing-components.herokuapp.com/component-guide/layout_for_admin). Ideally, we would have migrated all our applications to use the new Design System and publishing components, however there are still several in active use which still rely on govuk-admin-template. The GitHub project is archived, and is therefore read-only.
This RFC proposes un-archiving the project to allow iterative accessibility fixes to be applied to live applications.
Importantly, this RFC _does not_ propose removing the deprecation notice, or advocate …
=> RFC-145 unarchive govuk admin template

rfc-147-enable-speedcurve-http-protocol-capture.md
Allow SpeedCurve to capture a user's HTTP Protocol for use as a comparison dimension in the GUI.
✨ [Rendered](https://github.com/alphagov/govuk-rfcs/blob/103acd22a74b32d4ea9dd321bc0ab05ac664aa82/rfc-147-enable-speedcurve-http-protocol-capture.md) ✨ 
**Deadline**: 2022-05-10
=> RFC-147 - Allow SpeedCurve to capture a user's HTTP Protocol data

rfc-126-custom-configuration-for-dependabot.md, rfc-153-remove-allowlists-from-dependabot-configs.md, rfc-153-revert-rfc-126.md
Read the [rendered version](https://github.com/alphagov/govuk-rfcs/blob/revert-rfc-126/rfc-153-remove-allowlists-from-dependabot-configs.md) ⭐ 💅 
**Please comment by end of day 15th August**.
Trello: https://trello.com/c/nqliwwxV/2952-investigate-how-to-fix-dependabot-not-raising-security-prs
=> RFC 153 - Remove allowlists from Dependabot configs

rfc-154-integrating-an-ots-cms-with-govuk-for-custom-pages.md
Trello: https://trello.com/c/tpDtfZ7f/324-put-together-rfc-request-for-comments-on-introducing-a-3rd-party-cms-to-govuk
[👉 Rendered version 👈 ](https://github.com/alphagov/govuk-rfcs/blob/ots-cms/rfc-154-integrating-an-ots-cms-with-govuk-for-custom-pages.md)
Deadline for comments: November 3rd
This explains the proposed approach GOV.UK Publishing are taking considering which would enable the integration of an off-the-shelf CMS with GOV.UK for an experiment.
=> RFC-154 - Integrating a CMS with GOV.UK to power custom pages

rfc-156-auto-merge-internal-prs.md
Proposal to auto-merge Dependabot PRs for internal dependencies (under strict conditions) to ease burden of keeping code up to date.
[Rendered version](https://github.com/alphagov/govuk-rfcs/blob/auto-merge-internal-prs/rfc-156-auto-merge-internal-prs.md) 💅 
Trello: https://trello.com/c/rMDuLxbf/3073-evaluate-auto-merge-spike-and-write-rfc
=> RFC-156: Allow auto-merging of 'internal' Dependabot PRs

rfc-159-switch-off-whitehall-apis.md
Proposal to switch off Whitehall's public APIs.
[Rendered version](https://github.com/alphagov/govuk-rfcs/blob/remove-whitehall-apis/rfc-159-switch-off-whitehall-apis.md)
Deadline for comments: 25th May 2023.
[Trello card](https://trello.com/c/XdrGoInH)
=> RFC-159: switch off Whitehall's public APIs

rfc-095-long-term-future-apps.md, rfc-161-technical-direction-in-publishing-2023.md
View ✨ [rendered](https://github.com/alphagov/govuk-rfcs/blob/tech-direction-publishing-2023/rfc-161-technical-direction-in-publishing-2023.md) ✨ 
Deadline for comments: 31st July 2023
---
This RFC is to document opinions and approaches that have been discussed in the Publishing directorate over the last year or so. For those who've been in publishing a while, there isn't expected to be any huge surprises (and please feedback if there is).
The motivation for putting this together was that: Publishing has grown rapidly and continues to have frequent people changes; Kevin and Al (lead tech in Publishing) were about to go months without working together and wanted to document the current thinking; and that we have outdated directional information in [RFC-95][1].
It's welcome for other …
=> RFC-161 - Technical Direction in Publishing 2023

rfc-165-add-api-endpoints-to-transition.md
[Trello](https://trello.com/c/Pr1sKak1) 
Deadline for comments: 10th November
[Rendered version](https://github.com/alphagov/govuk-rfcs/blob/rfc-165-transition-bouncer-api/rfc-165-add-api-endpoints-to-transition.md)
=> RFC 165 - Add API endpoints to Transition for consumption by Bouncer

rfc-167-auto-patch-dependencies.md
View [rendered version](https://github.com/alphagov/govuk-rfcs/blob/auto-merge-dependencies/rfc-167-auto-patch-dependencies.md) 💅 
Please leave any comments by **Friday 23rd February**.
=> RFC-167: Allow auto-patching of external dependencies

README.md
This updates the process to reflect that RFCs should have a deadline and that senior tech members are the final voice of whether an RFC is accepted. I'm surprised this wasn't previously documented.
It also replaces notes about how to manage Action Plans, Standards and archiving since those concepts have never become established.
=> Update process documentation to reflect used conventions

rfc-177-edition-all-content.md
Adds RFC-177, which proposes making all content types editionable.
Deadline for comments: Monday 23rd September 2024.
[Rendered view](https://github.com/alphagov/govuk-rfcs/blob/rfc-177/rfc-177-edition-all-content.md)
[Trello card](https://trello.com/c/YZrRcF9o)
=> RFC-177: Make all content types editionable

rfc-177-edition-all-content.md
The status should have been updated to `accepted` when this RFC was merged, so updating it now to avoid any confusion.
[Trello card](https://trello.com/c/YZrRcF9o)
=> Update status for RFC-177
